### ISSUE TITLE
NameError: name 'filters' is not defined

### ISSUE THREAD

**Issue by ziprawan** [rushkii/pyrogram-cooldown#1]
I got this error while running the examples

```
Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Traceback (most recent call last):
  File "run.py", line 19, in <module>
    bot.start()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/utilities/start.py", line 68, in start
    await self.initialize()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/auth/initialize.py", line 44, in initialize
    self.load_plugins()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/client.py", line 736, in load_plugins
    module = import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/aziz/pyrogram-cooldown/plugins/echo.py", line 6, in <module>
    @bot.on_message(filters.command(['test']) & cooldown.wait(5))
  File "/home/aziz/pyrogram-cooldown/plugins/utils/cooldown.py", line 36, in wait
    return filters.create(___, data=sec)
NameError: name 'filters' is not defined
```

It's can be fixed by importing pyrogram.filters on cooldown.py

**Comment by rushkii** [comment]
Oh, sorry I didn't notice that. I will close this issue, thanks.
